spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simple-coffee-order?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false